version: 2

sources:
  - name: tpch
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: customer
        description: TPC-H Customer table
      - name: orders
        description: TPC-H Orders table
